# --- Part-of-speech tags for parsing ---
POS_TAGS = {
    'a': 'DET',
    'the': 'DET',
    'large': 'ADJ',
    'small': 'ADJ',
    'red': 'ADJ',
    'green': 'ADJ',
    'blue': 'ADJ',
    'tall': 'ADJ',
    'wide': 'ADJ',
    'deep': 'ADJ',
    'cube': 'NOUN',
    'box': 'NOUN',
    'sphere': 'NOUN',
    'arch': 'NOUN',
    'object': 'NOUN',
    'draw': 'VERB',
    'move': 'VERB',
    'delete': 'VERB',
    'on': 'PREP',
    'over': 'PREP',
    'under': 'PREP',
    'above': 'PREP',
    'below': 'PREP',
    'with': 'PREP',
    'to': 'PREP',
    'from': 'PREP',
    'in': 'PREP',
    'at': 'PREP',
    'by': 'PREP',
    'near': 'PREP'
}

