from engraf.lexer.vector_space import vector_from_features

SEMANTIC_VECTOR_SPACE = {
    # Nouns
    'cube': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'box': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'sphere': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'arch': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'object': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'square': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'rectangle': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'triangle': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'circle': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'cylinder': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'cone': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'tetrahedron': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'octahedron': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'dodecahedron': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'icosahedron': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'pyramid': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'prism': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]), 
    # Pronouns
    'it': vector_from_features("pronoun singular"),
    'they': vector_from_features("pronoun plural"),
    'them': vector_from_features("pronoun plural"),
     # Adjectives
    'red': vector_from_features("adj", color=[1.0, 0.0, 0.0]),
    'green': vector_from_features("adj", color=[0.0, 1.0, 0.0]),
    'blue': vector_from_features("adj", color=[0.0, 0.0, 1.0]),
    'yellow': vector_from_features("adj", color=[1.0, 1.0, 0.0]),
    'purple': vector_from_features("adj", color=[0.5, 0.0, 0.5]),
    'orange': vector_from_features("adj", color=[1.0, 0.5, 0.0]),
    'black': vector_from_features("adj", color=[0.0, 0.0, 0.0]),
    'white': vector_from_features("adj", color=[1.0, 1.0, 1.0]),
    'gray': vector_from_features("adj", color=[0.5, 0.5, 0.5]),
    'large': vector_from_features("adj", scale=[2.0, 2.0, 2.0]),
    'small': vector_from_features("adj", scale=[-0.5, -0.5, -0.5]),
    'tall': vector_from_features("adj", scale=[0.0, 1.5, 0.0]),
    'wide': vector_from_features("adj", scale=[1.5, 0.0, 0.0]),
    'deep': vector_from_features("adj", scale=[0.0, 0.0, 1.5]),
    # Adverbs
    'very': vector_from_features("adv", scale=[1.5, 1.5, 1.5], color=[1.5, 1.5, 1.5]),
    'extremely': vector_from_features("adv", scale=[2.0, 2.0, 2.0], color=[2.0, 2.0, 2.0]),
    'slightly': vector_from_features("adv", scale=[0.5, 0.5, 0.5], color=[0.5, 0.5, 0.5]),
    # Determiners
    'the': vector_from_features("det def", number=1.0),
    'one': vector_from_features("det def", number=1.0),
    'two': vector_from_features("det def", number=2.0),
    'three': vector_from_features("det def", number=3.0),
    'four': vector_from_features("det def", number=4.0),
    'five': vector_from_features("det def", number=5.0),
    'six': vector_from_features("det def", number=6.0),
    'seven': vector_from_features("det def", number=7.0),
    'eight': vector_from_features("det def", number=8.0),
    'nine': vector_from_features("det def", number=9.0),
    'ten': vector_from_features("det def", number=10.0),
    'a': vector_from_features("det", number=1.0),
    'an': vector_from_features("det", number=1.0),
    # Verbs
    'draw': vector_from_features("verb"),
    'move': vector_from_features("verb"),
    'delete': vector_from_features("verb"),
    'create': vector_from_features("verb"),
    'rotate': vector_from_features("verb"),
    'scale': vector_from_features("verb"),
    'color': vector_from_features("verb"),
    'select': vector_from_features("verb"),
    'place': vector_from_features("verb"),
    'position': vector_from_features("verb"),
    'align': vector_from_features("verb"),
    'group': vector_from_features("verb"),
    'ungroup': vector_from_features("verb"),
    'copy': vector_from_features("verb"),
    'paste': vector_from_features("verb"),
    'undo': vector_from_features("verb"),
    'redo': vector_from_features("verb"),
    # Prepositions
    'on': vector_from_features("prep"),
    'over': vector_from_features("prep"),
    'under': vector_from_features("prep"),
    'above': vector_from_features("prep"),
    'below': vector_from_features("prep"),
    'with': vector_from_features("prep"),
    'to': vector_from_features("prep"),
    'from': vector_from_features("prep"),
    'in': vector_from_features("prep"),
    'at': vector_from_features("prep"),
    'by': vector_from_features("prep"),
    'near': vector_from_features("prep")
}
