from engraf.lexer.vector_space import vector_from_features

SEMANTIC_VECTOR_SPACE = {
    'cube': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'box': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'sphere': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'arch': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'object': vector_from_features("noun", loc=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0]),
    'red': vector_from_features("adj", color=[1.0, 0.0, 0.0]),
    'green': vector_from_features("adj", color=[0.0, 1.0, 0.0]),
    'blue': vector_from_features("adj", color=[0.0, 0.0, 1.0]),
    'yellow': vector_from_features("adj", color=[1.0, 1.0, 0.0]),
    'purple': vector_from_features("adj", color=[0.5, 0.0, 0.5]),
    'orange': vector_from_features("adj", color=[1.0, 0.5, 0.0]),
    'black': vector_from_features("adj", color=[0.0, 0.0, 0.0]),
    'white': vector_from_features("adj", color=[1.0, 1.0, 1.0]),
    'gray': vector_from_features("adj", color=[0.5, 0.5, 0.5]),
    'large': vector_from_features("adj", scale=[2.0, 2.0, 2.0]),
    'small': vector_from_features("adj", scale=[-0.5, -0.5, -0.5]),
    'tall': vector_from_features("adj", scale=[0.0, 1.5, 0.0]),
    'wide': vector_from_features("adj", scale=[1.5, 0.0, 0.0]),
    'deep': vector_from_features("adj", scale=[0.0, 0.0, 1.5]),
    'the': vector_from_features("det def"),
    'a': vector_from_features("det"),
    'draw': vector_from_features("verb"),
    'move': vector_from_features("verb"),
    'delete': vector_from_features("verb"),
    'on': vector_from_features("prep"),
    'over': vector_from_features("prep"),
    'under': vector_from_features("prep"),
    'above': vector_from_features("prep"),
    'below': vector_from_features("prep"),
    'with': vector_from_features("prep"),
    'to': vector_from_features("prep"),
    'from': vector_from_features("prep"),
    'in': vector_from_features("prep"),
    'at': vector_from_features("prep"),
    'by': vector_from_features("prep"),
    'near': vector_from_features("prep")
}
