import numpy as np
from engraf.atn.np import build_np_atn
from engraf.lexer.token_stream import TokenStream, tokenize
from engraf.atn.subnet_np import run_np
from engraf.lexer.vector_space import VectorSpace, vector_from_features

input = [
"DRAW A ROUGH RED CIRCLE AT -1, 2.2, 5.55",
"MOVE A CIRCLES TO 3, 4, 5",
"MOVE 3 CIRCLES TO 3, 4, 5",
"MOVE THE BLUE CIRCLE TO 3, 4, 5",
"MOVE THE ROUGH CIRCLE TO 3, 4, 5",
"MOVE IT TO 3, 3, 3",
"MAKE THEM LARGE",
"MAKE IT VERY TALL",
"MAKE IT MUCH MORE TRANSPARENT AND ROUGHER",
"NO, MAKE IT MUCH MORE TRANSPARENT AND A TEENSY BIT ROUGHER",
"COLOR IT A LITTLE BIT REDDER",
"NO, COLOR IT PURPLE",
"XROTATE IT 45 DEGREES AND YROTATE IT 27 DEGREES",
"DRAW 3 VERY SMOOTH SHORT AND VERY OPAQUE BOXES",
"MOVE 2 OF THEM TO 1, 2, 3",
"MAKE THEM MORE TRANSPARENT THAN THE PURPLE CIRCLE AT 3, 3, 3",
"COLOR 4 OF THEM BLUE GREEN",
"MAKE 1 OF THEM AS ROUGH AS THE PURPLE CIRCLE AND MAKE THE REST OF THEM SMOOTH",
"REMOVE A BOX AT 1, 2, 3",
"REMOVE THE TALL BOX AT 1, 2, 3",
"COLOR A BOX TALL",
"DRAW A TALL RED BOX AND A SMALL BRIGHT BLUE CIRCLE",
"COLOR A TALL BOX GREEN AND MOVE IT TO 7, 7, 7",
"DRAW 3 CIRCLES AT 3, 6, 9 AND COLOR TWO OF THEM RED",
"GO BACK IN TIME",
"GO FORWARD IN TIME",
"GO FORWARD IN TIME",
"GO FORWARD IN TIME",
"'HUGE' IS VERY LARGE",
"'SKY BLUE' IS BLUE AND GREEN",
"DRAW A HUGE SKY BLUE BOX"
]
input_lower = [s.lower() for s in input]